#=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - ../cases/logstash/beats/case_single_json/*.json
#  multiline.pattern: "^{"
#  multiline.negate: true
#  multiline.match: after
#  multiline.max_lines: 0

#============================= Filebeat modules ===============================

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

#==================== Elasticsearch template setting ==========================

setup.template.settings:
  index.number_of_shards: 3
  #index.codec: best_compression
  #_source.enabled: false

#-------------------------- Elasticsearch output ------------------------------
#output.elasticsearch:
  # Array of hosts to connect to.
  #hosts: ["localhost:9200"]

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5000"]
  username: "elastic"
  password: "changeme"

processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: false
      target: ""
      overwrite_keys: false
  - add_host_metadata: ~
  - add_cloud_metadata: ~
